version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm run start"
    ports:
      - 443:443
    volumes:
      - ./certs:/app/certs
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_ADMIN_API_URL=${NEXT_PUBLIC_ADMIN_API_URL}
      - PORT=443
