version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm run dev"
    ports:
      - 80:3000
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=3000
