name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker-compose


            rm -rf KSNet-frontend
            git clone https://github.com/aivanns/KSNet-frontend.git
            cd KSNet-frontend

            mkdir -p certs
            cd certs
            openssl req -nodes -new -x509 -keyout private.key -out certificate.crt -days 365 -subj "/CN=ubase-cloud.ru"

            cd ..
            
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env 
            echo "NEXT_PUBLIC_ADMIN_API_URL=${{ secrets.NEXT_PUBLIC_ADMIN_API_URL }}" >> .env

            cat .env

            docker-compose down -v

            docker-compose up --build -d
  
